<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle() ?>
	<?php echo $this->headLink() ?>
	<?php echo $this->headScript() ?>
	<?php echo isset($this->google_analytics)?$this->google_analytics:"" ?>
</head>
<body>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-55N6NH"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-55N6NH');</script>
<!-- End Google Tag Manager -->

<?php echo $this->partial('partialviews/airtimeproctabar.phtml'); ?>

    <div id="login-page">
        <?php echo $this->layout()->content ?>
    </div>
    <div class="footer">
      <?php echo sprintf(_("Airtime copyright &copy; Sourcefabric z.ú. All rights reserved.%s"
      ."Maintained and distributed under the GNU GPL v.3 by %sSourcefabric z.ú.%s"),
      "<br>", "<a href='http://www.sourcefabric.org'>" ,"</a>");?> 
    </div>
 
</body>
</html>
