<div class="crossfade clearfix" style="display: none">
	<dl id="spl_editor" class="inline-list">
		<dd>
			<input type="button" class="pl-waveform-fades-btn" value="<?php echo _("Show Waveform")?>"></input>
		</dd>
		<dt><?php echo _("Fade in: "); ?>
			<span class='spl_cue_hint'><?php echo _("(ss.t)")?></span>
		</dt>
		<dd id="spl_fade_in_<?php echo $this->id; ?>" class="spl_fade_in" 
			data-fade="<?php echo $this->fadeIn; ?>">
		    <span contenteditable="true" class="spl_text_input spl_soe"><?php echo $this->fadeIn; ?></span>
		</dd>
		<dt><?php echo _("Fade out: "); ?>
			<span class='spl_cue_hint'><?php echo _("(ss.t)")?></span>
		</dt>
		<dd id="spl_fade_out_<?php echo $this->id; ?>" class="spl_fade_out" 
		   	data-fade="<?php echo $this->fadeOut; ?>">
		    <span contenteditable="true" class="spl_text_input spl_soe"><?php echo $this->fadeOut; ?></span>
		</dd>
	</dl>
</div>
