<div class="text-content">
    <h2><?php echo _("About") ?></h2>
<p>
<?php 

$productSiteAnchor = "<a href='" . PRODUCT_SITE_URL . "' target='_blank'>"
                        . PRODUCT_NAME
                    . "</a>";
echo sprintf(_('%1$s %2$s, the open radio software for scheduling and remote station management.'),
    $productSiteAnchor,
    $this->airtime_version)
?>
<br />
<?php 
if ($this->is_fork) {
$forkAnchor = '<a href="' . AIRTIME_FORK_URL . '" target="_blank">'
                 . AIRTIME_FORK_NAME
             . '</a>'; 
echo sprintf('%1$s %2$s, %3$s<br />',
    $forkAnchor, AIRTIME_FORK_VERSION, AIRTIME_FORK_DESCRIPTION);
}
?>
<br />© 2013 
<?php 
$companySiteAnchor = "<a href='" . COMPANY_SITE_URL . "' target='_blank'>"
                        . COMPANY_NAME . " " . COMPANY_SUFFIX
                    . "</a>";
$licenseAnchor = "<a href='" . LICENSE_URL . "' target='_blank'>"
                    . LICENSE_VERSION
                . "</a>";
echo sprintf(_('%1$s %2$s is distributed under the %3$s'),
    $companySiteAnchor, PRODUCT_NAME, $licenseAnchor)
?>
</p>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
