<div class="ui-widget ui-widget-content block-shadow simple-formblock clearfix padded full_width">
	<table width="60%" cellpadding="0" cellspacing="0" class="statustable datatable">
	    <thead>
	        <tr class="ui-state-default strong">
	            <td><?php echo _("Service") ?></td>
	            <td><?php echo _("Status") ?></td>
	            <td><?php echo _("Uptime") ?></td>
	            <td><?php echo _("CPU") ?></td>
	        	<td><?php echo _("Memory") ?></td>
	        </tr>
	    </thead>
	    <tbody>
	        <?php $i=0; ?>
	        <?php foreach($this->status->services as $key=>$value): ?>
	            <tr class="<?php echo ($i&1) == 0 ? "even":"odd"; $i++; ?>" id="<?php echo $value["name"]; ?>">
	                <td><?php echo $value["name"]; ?></td>
	                <td><span></span></td>
	                <td></td>
	                <td></td>
	                <td></td>
	            </tr>
	        <?php endforeach; ?>
	        <tr id="partitions" class="even">
	        	<th colspan="5"><?php echo _("Disk Space") ?></th>
	        </tr>
	    </tbody>
	</table> 
</div>
